name: Build Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v5
        with:
          path: web/node_modules
          key: ${{ runner.os }}-node-modules

      - name: Install Dependencies
        working-directory: ./web
        run: |
          npm install
      - name: Build
        working-directory: ./web
        run: |
          npm run build

      - uses: actions/upload-artifact@v7
        with:
          name: ui
          path: web/dist/

  backend:
    needs: frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - name: Retrieve UI build
        uses: actions/download-artifact@v5
        with:
          name: ui
          path: web/dist/

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Prepare cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --target ${{ matrix.toolchain }} --features ui --package safe_house --bin safe_house --profile release --verbose

      - uses: actions/upload-artifact@v7
        with:
          name: server-${{ matrix.toolchain }}
          path: target/${{ matrix.toolchain }}/release/safe_house